"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../../public/assets/css/main.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/sass/main.scss";
import "../../public/assets/css/jquery-ui.css";
import "../../public/assets/sass/main.scss";
import "select2/dist/css/select2.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import reportWebVitals from "./reportWebVitals";
// import RouteScrollToTop from "../helper/RouteScrollToTop";
import PhosphorIconInit from "../helper/PhosphorIconInit";
import dynamic from "next/dynamic";
export const Slider = dynamic(() => import("react-slick"), { ssr: false });
export const ReactSlider = dynamic(() => import("react-slick"), { ssr: false });
import BottomTab from "../components/BottomTab";
import Header from "../components/Header";
import FooterTwo from "../components/FooterTwo";
import BottomFooter from "../components/BottomFooter";
import ShippingTwo from "../components/ShippingTwo";
import NewsletterTwo from "../components/NewsletterTwo";
import SidebarOptions from "@/components/SidebarOptions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ overflow: "hidden" }}
      >
        {/* <RouteScrollToTop /> */}

        <PhosphorIconInit />
        <Header />
        <div
          className="container-fluid"
          style={{ height: "100vh", overflow: "hidden" }}
        >
          <div className="row h-100" style={{ overflow: "hidden" }}>
            <aside
              className="d-none d-lg-block col-2 border h-100"
              style={{ position: "sticky", top: 0 }}
            >
              <SidebarOptions />
            </aside>

            <main
              className="col-sm-12 col-md-10"
              style={{
                height: "100vh",
                overflowY: "scroll",
                msOverflowStyle: "none" /* IE and Edge */,
                scrollbarWidth: "none" /* Firefox */,
              }}
            >
              {children}
              <footer>
                <ShippingTwo />
                <NewsletterTwo />
                <FooterTwo />
                <BottomFooter />
              </footer>
            </main>
          </div>
        </div>
        <BottomTab />
      </body>
    </html>
  );
}
reportWebVitals();
