// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../../public/assets/css/main.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/sass/main.scss";
import "../../public/assets/css/jquery-ui.css";
import "../../public/assets/sass/main.scss";

import "select2/dist/css/select2.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import reportWebVitals from "./reportWebVitals";

import dynamic from "next/dynamic";
export const Slider = dynamic(() => import("react-slick"), { ssr: false });
export const ReactSlider = dynamic(() => import("react-slick"), { ssr: false });
import HeaderTwo from "../components/HeaderTwo";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeaderTwo category={false} />
        {children}
      </body>
    </html>
  );
}
reportWebVitals();
